### ISSUE TITLE
TemplateNotFound jinja2.exceptions.TemplateNotFound: .html

### ISSUE THREAD

**Issue by icloudsolutions** [icloudsolutions/cashdrawer_rs232#12]
TemplateNotFound
jinja2.exceptions.TemplateNotFound: home.html

Traceback (most recent call last)
File "flask\app.py", line 1488, in __call__
File "flask\app.py", line 1466, in wsgi_app
File "flask\app.py", line 1463, in wsgi_app
File "flask\app.py", line 872, in full_dispatch_request
File "flask\app.py", line 870, in full_dispatch_request
File "flask\app.py", line 855, in dispatch_request

![Capture](https://github.com/icloudsolutions/cashdrawer_rs232/assets/151461104/9eef5b44-cdf9-4d83-999a-daa5a8b68b77)

**Comment by icloudsolutions** [comment]
include html files in cashdrawer_rs232.spec and recompile code with : pyinstaller cashdrawer_rs232.spec

# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['cashdrawer_rs232.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('templates', 'templates'),
        ('static', 'static')
    ],
    hiddenimports=[],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='cashdrawer_rs232',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)

**Comment by icloudsolutions** [comment]
![Capture](https://github.com/icloudsolutions/cashdrawer_rs232/assets/151461104/c3c1815a-4ce3-456e-998b-3c1c2a667765)
